export const data = [
	{
		id: 1,
		marque: "Cartier",
		modele: "Dumont",
		img: "/images/dumont.webp",
	},
	{
		id: 2,
		marque: "Rolex",
		modele: "GMT - Bruce Wayne",
		img: "/images/gmt.jpeg",
	},
	{
		id: 3,
		marque: "Cartier",
		modele: "Panthère",
		img: "/images/panthere.webp",
	},
	{
		id: 4,
		marque: "Cartier",
		modele: "Santos",
		img: "/images/santos.webp",
	},
	{
		id: 5,
		marque: "Vacheron",
		modele: "222",
		img: "/images/222.avif",
	},
	{
		id: 6,
		marque: "Cartier",
		modele: "2960",
		img: "/images/2960.jpg",
	},
	{
		id: 7,
		marque: "Tudor",
		modele: "Black-bay",
		img: "/images/blackbay.avif",
	},
	{
		id: 8,
		marque: "Patek Philippe",
		modele: "Cubitus",
		img: "/images/cubitus.webp",
	},
	{
		id: 9,
		marque: "Rolex",
		modele: "Date-Just",
		img: "/images/datejust.jpg",
	},
	{
		id: 10,
		marque: "Rolex",
		modele: "Daytona",
		img: "/images/daytona.avif",
	},
	{
		id: 11,
		marque: "Rolex",
		modele: "Explorer",
		img: "/images/explorer.avif",
	},
	{
		id: 12,
		marque: "Patek-Philippe",
		modele: "Golden Ellipse",
		img: "/images/golden.jpg",
	},
	{
		id: 13,
		marque: "Grand Seiko",
		modele: "SGBA 407",
		img: "/images/gseiko.webp",
	},
	{
		id: 14,
		marque: "Patek-Philippe",
		modele: "Nautilus",
		img: "/images/nautilus.jpg",
	},
	{
		id: 15,
		marque: "Rolex",
		modele: "Oyster",
		img: "/images/oyster.avif",
	},
	{
		id: 16,
		marque: "Tudor",
		modele: "Pelagos",
		img: "/images/pelagos.jpg",
	},
	{
		id: 17,
		marque: "Audemars Piguet",
		modele: "Royal oak",
		img: "/images/royal-oak.jpg",
	},
	{
		id: 18,
		marque: "Tudor",
		modele: "Royal",
		img: "/images/royal.avif",
	},
	{
		id: 19,
		marque: "Rolex",
		modele: "Submariner",
		img: "/images/submariner.webp",
	},
];
